ignoredBuiltDependencies:
  - bufferutil
  - esbuild
  - utf-8-validate

onlyBuiltDependencies:
  - bufferutil@4.1.0
  - esbuild@0.18.20
  - esbuild@0.25.12
  - esbuild@0.27.4
  - utf-8-validate@6.0.6
